project_id = "tthzcijscedgxjfnfnky"

[api]
enabled = true
url = "https://tthzcijscedgxjfnfnky.supabase.co/functions/v1"

[[fetch.resources]]
name = "resend"
url = "https://api.resend.com"

[functions.create-admin-user]
verify_jwt = false