-- ============================================================
-- Doc'O Clock — provider profession module charter
--
-- Every profession chosen at provider signup gets its workspace modules
-- chartered: status = 'live' -> shipped in the app,
-- status = 'planned' -> chartered now, built later.
-- The ProviderDashboard reads this table for the signed-in provider's
-- profession, so the choice at signup drives their workspace.
-- Idempotent; safe to re-run.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.provider_module_charter (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_type text NOT NULL,
  module_key text NOT NULL,
  module_name text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'planned' CHECK (status IN ('live', 'planned')),
  display_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider_type, module_key)
);

INSERT INTO public.provider_module_charter
  (provider_type, module_key, module_name, description, status, display_order)
VALUES
  ('doctor', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('doctor', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('doctor', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('doctor', 'prescriptions', 'E-prescriptions', 'Write electronic prescriptions', 'live', 4),
  ('doctor', 'lab_orders', 'Lab test orders', 'Order tests and receive results', 'live', 5),
  ('doctor', 'vitals', 'Vitals capture', 'Record triage vital signs', 'planned', 6),
  ('doctor', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 7),
  ('doctor', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 8),
  ('doctor', 'patients', 'My patients', 'Patient list and histories', 'live', 9),
  ('doctor', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 10),
  ('doctor', 'reports', 'Practice reports', 'Volume and revenue reports', 'planned', 11),
  ('specialist', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('specialist', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('specialist', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('specialist', 'prescriptions', 'E-prescriptions', 'Write electronic prescriptions', 'live', 4),
  ('specialist', 'lab_orders', 'Lab test orders', 'Order tests and receive results', 'live', 5),
  ('specialist', 'vitals', 'Vitals capture', 'Record triage vital signs', 'planned', 6),
  ('specialist', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 7),
  ('specialist', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 8),
  ('specialist', 'patients', 'My patients', 'Patient list and histories', 'live', 9),
  ('specialist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 10),
  ('specialist', 'reports', 'Practice reports', 'Volume and revenue reports', 'planned', 11),
  ('medical_licentiate', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('medical_licentiate', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('medical_licentiate', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('medical_licentiate', 'prescriptions', 'E-prescriptions', 'Write electronic prescriptions', 'live', 4),
  ('medical_licentiate', 'lab_orders', 'Lab test orders', 'Order tests and receive results', 'live', 5),
  ('medical_licentiate', 'vitals', 'Vitals capture', 'Record triage vital signs', 'planned', 6),
  ('medical_licentiate', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 7),
  ('medical_licentiate', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 8),
  ('medical_licentiate', 'patients', 'My patients', 'Patient list and histories', 'live', 9),
  ('medical_licentiate', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 10),
  ('medical_licentiate', 'reports', 'Practice reports', 'Volume and revenue reports', 'planned', 11),
  ('clinical_officer', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('clinical_officer', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('clinical_officer', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('clinical_officer', 'prescriptions', 'E-prescriptions', 'Write electronic prescriptions', 'live', 4),
  ('clinical_officer', 'lab_orders', 'Lab test orders', 'Order tests and receive results', 'live', 5),
  ('clinical_officer', 'vitals', 'Vitals capture', 'Record triage vital signs', 'planned', 6),
  ('clinical_officer', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 7),
  ('clinical_officer', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 8),
  ('clinical_officer', 'patients', 'My patients', 'Patient list and histories', 'live', 9),
  ('clinical_officer', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 10),
  ('clinical_officer', 'reports', 'Practice reports', 'Volume and revenue reports', 'planned', 11),
  ('dentist', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('dentist', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 2),
  ('dentist', 'dental_chart', 'Dental charting', 'Odontogram and treatment plans', 'planned', 3),
  ('dentist', 'prescriptions', 'E-prescriptions', 'Write electronic prescriptions', 'live', 4),
  ('dentist', 'lab_orders', 'Lab test orders', 'Order tests and receive results', 'live', 5),
  ('dentist', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 6),
  ('dentist', 'patients', 'My patients', 'Patient list and histories', 'live', 7),
  ('dentist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 8),
  ('dentist', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 9),
  ('dentist', 'reports', 'Practice reports', 'Volume and revenue reports', 'planned', 10),
  ('dental_therapist', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('dental_therapist', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 2),
  ('dental_therapist', 'dental_chart', 'Dental charting', 'Odontogram and treatment plans', 'planned', 3),
  ('dental_therapist', 'patients', 'My patients', 'Patient list and histories', 'live', 4),
  ('dental_therapist', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 5),
  ('dental_therapist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 6),
  ('dental_therapist', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 7),
  ('registered_nurse', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('registered_nurse', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('registered_nurse', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('registered_nurse', 'vitals', 'Vitals capture', 'Record triage vital signs', 'planned', 4),
  ('registered_nurse', 'ward_rounds', 'Ward rounds', 'Inpatient round notes', 'planned', 5),
  ('registered_nurse', 'patients', 'My patients', 'Patient list and histories', 'live', 6),
  ('registered_nurse', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 7),
  ('registered_nurse', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 8),
  ('registered_nurse', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 9),
  ('enrolled_nurse', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('enrolled_nurse', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('enrolled_nurse', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('enrolled_nurse', 'vitals', 'Vitals capture', 'Record triage vital signs', 'planned', 4),
  ('enrolled_nurse', 'ward_rounds', 'Ward rounds', 'Inpatient round notes', 'planned', 5),
  ('enrolled_nurse', 'patients', 'My patients', 'Patient list and histories', 'live', 6),
  ('enrolled_nurse', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 7),
  ('enrolled_nurse', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 8),
  ('enrolled_nurse', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 9),
  ('nurse', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('nurse', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('nurse', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('nurse', 'vitals', 'Vitals capture', 'Record triage vital signs', 'planned', 4),
  ('nurse', 'ward_rounds', 'Ward rounds', 'Inpatient round notes', 'planned', 5),
  ('nurse', 'patients', 'My patients', 'Patient list and histories', 'live', 6),
  ('nurse', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 7),
  ('nurse', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 8),
  ('nurse', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 9),
  ('midwife', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('midwife', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('midwife', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('midwife', 'vitals', 'Vitals capture', 'Record triage vital signs', 'planned', 4),
  ('midwife', 'ward_rounds', 'Ward rounds', 'Inpatient round notes', 'planned', 5),
  ('midwife', 'anc_register', 'ANC/PNC register', 'Antenatal and postnatal registers', 'planned', 6),
  ('midwife', 'patients', 'My patients', 'Patient list and histories', 'live', 7),
  ('midwife', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 8),
  ('midwife', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 9),
  ('midwife', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 10),
  ('pharmacist', 'dispense', 'Dispensing', 'Dispense and counsel on medicines', 'live', 1),
  ('pharmacist', 'prescriptions', 'E-prescriptions', 'Write electronic prescriptions', 'live', 2),
  ('pharmacist', 'stock', 'Medicine stock', 'Track dispensary stock', 'live', 3),
  ('pharmacist', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 4),
  ('pharmacist', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 5),
  ('pharmacist', 'patients', 'My patients', 'Patient list and histories', 'live', 6),
  ('pharmacist', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 7),
  ('pharmacist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 8),
  ('pharmacist', 'reports', 'Practice reports', 'Volume and revenue reports', 'planned', 9),
  ('pharmacy_technologist', 'dispense', 'Dispensing', 'Dispense and counsel on medicines', 'live', 1),
  ('pharmacy_technologist', 'stock', 'Medicine stock', 'Track dispensary stock', 'live', 2),
  ('pharmacy_technologist', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 3),
  ('pharmacy_technologist', 'patients', 'My patients', 'Patient list and histories', 'live', 4),
  ('pharmacy_technologist', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 5),
  ('pharmacy_technologist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 6),
  ('radiologist', 'imaging_queue', 'Imaging worklist', 'Radiology reporting worklist', 'planned', 1),
  ('radiologist', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 2),
  ('radiologist', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 3),
  ('radiologist', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 4),
  ('radiologist', 'lab_orders', 'Lab test orders', 'Order tests and receive results', 'live', 5),
  ('radiologist', 'patients', 'My patients', 'Patient list and histories', 'live', 6),
  ('radiologist', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 7),
  ('radiologist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 8),
  ('radiologist', 'reports', 'Practice reports', 'Volume and revenue reports', 'planned', 9),
  ('radiographer', 'imaging_queue', 'Imaging worklist', 'Radiology reporting worklist', 'planned', 1),
  ('radiographer', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 2),
  ('radiographer', 'patients', 'My patients', 'Patient list and histories', 'live', 3),
  ('radiographer', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 4),
  ('radiographer', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 5),
  ('pathologist', 'test_queue', 'Test queue & verification', 'Process and verify lab tests', 'live', 1),
  ('pathologist', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 2),
  ('pathologist', 'patients', 'My patients', 'Patient list and histories', 'live', 3),
  ('pathologist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 4),
  ('pathologist', 'reports', 'Practice reports', 'Volume and revenue reports', 'planned', 5),
  ('pathologist', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 6),
  ('lab_technician', 'test_queue', 'Test queue & verification', 'Process and verify lab tests', 'live', 1),
  ('lab_technician', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 2),
  ('lab_technician', 'patients', 'My patients', 'Patient list and histories', 'live', 3),
  ('lab_technician', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 4),
  ('lab_technician', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 5),
  ('physiotherapist', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('physiotherapist', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('physiotherapist', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('physiotherapist', 'rehab_plans', 'Rehabilitation care plans', 'Physio/OT care plans and sessions', 'planned', 4),
  ('physiotherapist', 'patients', 'My patients', 'Patient list and histories', 'live', 5),
  ('physiotherapist', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 6),
  ('physiotherapist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 7),
  ('physiotherapist', 'reports', 'Practice reports', 'Volume and revenue reports', 'planned', 8),
  ('physiotherapist', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 9),
  ('occupational_therapist', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('occupational_therapist', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('occupational_therapist', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('occupational_therapist', 'rehab_plans', 'Rehabilitation care plans', 'Physio/OT care plans and sessions', 'planned', 4),
  ('occupational_therapist', 'patients', 'My patients', 'Patient list and histories', 'live', 5),
  ('occupational_therapist', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 6),
  ('occupational_therapist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 7),
  ('occupational_therapist', 'reports', 'Practice reports', 'Volume and revenue reports', 'planned', 8),
  ('occupational_therapist', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 9),
  ('nutritionist', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('nutritionist', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('nutritionist', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('nutritionist', 'nutrition_plans', 'Nutrition care plans', 'Meal plans and diet follow-up', 'planned', 4),
  ('nutritionist', 'patients', 'My patients', 'Patient list and histories', 'live', 5),
  ('nutritionist', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 6),
  ('nutritionist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 7),
  ('optometrist', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('optometrist', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 2),
  ('optometrist', 'vision_tests', 'Vision test records', 'Refraction and eye test records', 'planned', 3),
  ('optometrist', 'prescriptions', 'E-prescriptions', 'Write electronic prescriptions', 'live', 4),
  ('optometrist', 'patients', 'My patients', 'Patient list and histories', 'live', 5),
  ('optometrist', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 6),
  ('optometrist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 7),
  ('optometrist', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 8),
  ('psychologist', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('psychologist', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('psychologist', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('psychologist', 'therapy_notes', 'Therapy session notes', 'Counselling session notes', 'planned', 4),
  ('psychologist', 'patients', 'My patients', 'Patient list and histories', 'live', 5),
  ('psychologist', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 6),
  ('psychologist', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 7),
  ('environmental_health_officer', 'field_visits', 'Field visit log', 'Community field visits and screening', 'planned', 1),
  ('environmental_health_officer', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 2),
  ('environmental_health_officer', 'patients', 'My patients', 'Patient list and histories', 'live', 3),
  ('environmental_health_officer', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 4),
  ('environmental_health_officer', 'reports', 'Practice reports', 'Volume and revenue reports', 'planned', 5),
  ('community_health_worker', 'field_visits', 'Field visit log', 'Community field visits and screening', 'planned', 1),
  ('community_health_worker', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 2),
  ('community_health_worker', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 3),
  ('community_health_worker', 'patients', 'My patients', 'Patient list and histories', 'live', 4),
  ('community_health_worker', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 5),
  ('traditional_practitioner', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('traditional_practitioner', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 2),
  ('traditional_practitioner', 'patients', 'My patients', 'Patient list and histories', 'live', 3),
  ('traditional_practitioner', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 4),
  ('traditional_practitioner', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 5),
  ('health_personnel', 'appointments', 'Appointments & day list', 'Manage bookings and the daily queue', 'live', 1),
  ('health_personnel', 'telehealth', 'Telehealth video consults', 'Video consultations with patients', 'live', 2),
  ('health_personnel', 'consultations', 'Consultation notes', 'Record consultations in the patient EMR', 'live', 3),
  ('health_personnel', 'prescriptions', 'E-prescriptions', 'Write electronic prescriptions', 'live', 4),
  ('health_personnel', 'patients', 'My patients', 'Patient list and histories', 'live', 5),
  ('health_personnel', 'billing', 'Billing & payments', 'Invoices, receipts and mobile-money', 'live', 6),
  ('health_personnel', 'schedule', 'Working hours & availability', 'Set availability for bookings', 'live', 7),
  ('health_personnel', 'referrals', 'Referrals', 'Refer patients to facilities and specialists', 'planned', 8)
ON CONFLICT (provider_type, module_key) DO NOTHING;
